AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorldHandler.HelloWorldFunction
      Runtime: nodejs10.x
      CodeUri: ./
      Role: arn:aws:iam::741922737521:role/david-ting-helloworld-stack-HelloWorldFunctionRole-15TUPVGCZUX61
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
