AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for HelloWorldAPI

Globals:
  Function:
    Runtime: nodejs10.x
    CodeUri: ./

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorldHandler.HelloWorldFunction
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

  GetPeopleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PeopleHandler.GetPeopleFunction
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /people
            Method: GET

  AddToPeopleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PeopleHandler.AddToPeopleFunction
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /people
            Method: POST

  DeletePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PersonHandler.DeletePersonFunction
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /people/{name}
            Method: DELETE

  UpdatePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PersonHandler.UpdatePersonFunction
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /people/{name}
            Method: PUT
